### ISSUE TITLE
Create benchmarks to measure time for retrieving recommendations for selected cluster and rule

### ISSUE THREAD

**Issue by tisnik** [RedHatInsights/insights-results-smart-proxy#145]
Now we have a new REST API endpoint to retrieve recommendations for selected cluster and rule. It is implemented as filtering on backend side (basically for-loop in Go). It would be nice to have a knowledge how fast or slow is this implementation.

## Acceptance criteria

- [x] max time between request->response
- [x] min time between request->response
- [x] average time between request->response

**Comment by Sergey1011010** [comment]
The benchmark and the results are here https://github.com/Sergey1011010/benchmark-single-rule-endpoint if you need access, feel free to request it.

TL;DR:

![distribution](https://github.com/Sergey1011010/benchmark-single-rule-endpoint/blob/master/distribution-microseconds.png?raw=true)

minimum duration was 0.0 ms
maximum duration was 74.871 ms
average duration was 6.59129992942837 ms
