### ISSUE TITLE
Implement pull from insights-content-service and load content into in-memory structures

### ISSUE THREAD

**Issue by Bee-lee** [RedHatInsights/insights-results-smart-proxy#7]
The insights-content-service will now only provide all the content for OCP rules (descriptions, resolutions, etc.), as well as information about OCP rule groups (already implemented).

The rules' content will be pulled all at once from the content-service and loaded into in-memory structures to be retrieved quickly and joined with the analysis report without any further API calls / DB hits. 

As with the interface between smart-proxy and aggregator, no authentication is necessary, because the user is already authenticated in smart-proxy

Unknowns:
- transport format of the content. It would be inefficient to marshall and unmarshall a JSON into 1:1 structures, possibly `encoding/gob` pkg might be used

Out of scope:
- auto-updating mechanism of content from content-service
- checker for new changes in content

**Comment by Sergey1011010** [comment]
Doesn't it solve the same problem as cache(CCXDEV-1885) but using different approach?

**Comment by joselsegura** [comment]
@Sergey1011010 I think that this issue is related to the pull mechanism and the Jira is about the "auto-updating mechanism of content from content-service", that is out of the scope of the issue
