### ISSUE TITLE
MIssing /rules/{ruleId}/content endpoint in openapi.json

### ISSUE THREAD

**Issue by quarckster** [RedHatInsights/insights-results-smart-proxy#90]
`endpoints.go` has that endpoint in https://github.com/RedHatInsights/insights-results-smart-proxy/blob/master/server/endpoints.go#L36 but `openapi.json` missing it.

**Comment by joselsegura** [comment]
As part of the developing of a new endpoint I need to update the `openapi.json`, so probably I will add this endpoint to the spec too

**Comment by joselsegura** [comment]
Already updated in https://github.com/RedHatInsights/insights-results-smart-proxy/pull/153

**Comment by joselsegura** [comment]
https://github.com/RedHatInsights/insights-results-smart-proxy/blob/a6b594536686c0109d1b4b7468686fee0c42d3d5/openapi.json#L870
