### ISSUE TITLE
Improper program logic

### ISSUE THREAD

**Issue by tisnik** [RedHatInsights/insights-results-smart-proxy#985]
It looks like the `filtered` is set to `false` every time the error is thrown:
https://github.com/RedHatInsights/insights-results-smart-proxy/blob/7b4a01fa21341bed16daa8d928f33657ed568cd5/server/server.go#L1314

Is the program logic correct?

**Comment by dpensi** [comment]
yes, every time we have an error `filtered` is false, that if is redundant; here's the logic https://github.com/RedHatInsights/insights-results-smart-proxy/blob/master/content/content.go#L509
